<?php
	$collection = $block->getCollection();
if ($collection->count()) {
?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('ID') ?></th>
            <th scope="col" class="col first_name"><?php echo __(' First Name') ?></th>
            <th scope="col" class="col last_name"><?php echo __('Last Name') ?></th>
            <th scope="col" class="col email"><?php echo __('Email') ?></th>
            <th scope="col" class="col telephone"><?php echo __('Telephone') ?></th>
            <th scope="col" class="col create_at"><?php echo __('Created At') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
	
	foreach ($collection as $item): ?>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                <?php echo $item->getId() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('First Name')) ?>" class="col name">
                <?php echo $item->getName() ?>
	    <td data-th="<?= $block->escapeHtml(__('Last Name')) ?>" class="col name">
                <?php echo $item->getName() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col email">
                <?php echo $item->getEmail() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Telephone')) ?>" class="col telephone">
                <?php echo $item->getTelephone() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Created At')) ?>"
                class="col title"><?php echo date('Y-m-d', strtotime($item->getCreatedAt())); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
	}
	?>
